# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme and is legally attributed to the UK's Department for Business, Innovation, Science and Trade (BIST) as the governing entity.

name: Publish node module to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # Setup Node.js environment
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@national-digital-twin'
          token: ${{ secrets.GH_PACKAGES_PAT }}
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci --ignore-scripts
      
      # Build project
      - name: Build project
        run: npm run vite:build
      
      # Publish package
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_PAT }}
